### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by funcoding** [kontalk/emojicon#1]
Is there any working example for this library? I understood that this library is not compatible with rockerhieu/emojicon

> /example/MainActivity.java
> Error:(26, 31) error: cannot find symbol class EmojiconGridFragment
> Error:(28, 31) error: cannot find symbol class EmojiconsFragment
> Error:(31, 83) error: package EmojiconGridFragment does not exist
> Error:(31, 128) error: package EmojiconsFragment does not exist
> Error:(64, 42) error: cannot find symbol variable EmojiconsFragment
> Error:(70, 9) error: cannot find symbol variable EmojiconsFragment
> Error:(68, 5) error: method does not override or implement a method from a supertype
> Error:(75, 9) error: cannot find symbol variable EmojiconsFragment
> Error:(73, 5) error: method does not override or implement a method from a supertype
> Error:Execution failed for task ':example:compileDebugJava'.
>  Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED
> Information:Total time: 1 mins 20.968 secs
> Information:10 errors
> Information:0 warnings

**Comment by daniele-athome** [comment]
I'm currently using it in Kontalk Android client. Besides, it's a simple view that can be embedded anywhere and the source code is quite self-explainatory.
